import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

from . import models


def _bullet_list(items: list[str], style) -> list[Paragraph]:
    return [Paragraph(f"&bull; {i}", style) for i in items] or [Paragraph("None.", style)]


def build_incident_markdown(incident: models.Incident) -> str:
    """Formats an incident (title, timeline, MITRE techniques, risk, recommended actions,
    investigation summary) as clean markdown for pasting into a slide or email. Walks the
    exact same incident fields, in the same order, as build_incident_report_pdf above —
    two presentations of one data source, not a second report pipeline."""
    lines = [f"# {incident.title}", ""]
    lines.append(f"**Severity:** {incident.severity.upper()}  |  **Risk score:** {incident.risk_score}/100  |  **Status:** {incident.investigation_status}")
    lines.append("")

    entities = incident.entities or {}
    lines.append("## Entities")
    lines.append(f"- **Source IP(s):** {', '.join(entities.get('source_ips', [])) or '-'}")
    lines.append(f"- **Target IP(s):** {', '.join(entities.get('dest_ips', [])) or '-'}")
    lines.append(f"- **Host(s):** {', '.join(entities.get('hosts', [])) or '-'}")
    lines.append(f"- **User(s):** {', '.join(entities.get('users', [])) or '-'}")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append(incident.investigation_summary or "No investigation summary available.")
    lines.append("")

    lines.append("## Attack Timeline")
    if incident.timeline:
        for entry in incident.timeline:
            lines.append(f"- `{entry['timestamp']}` — {entry['description']}")
    else:
        lines.append("No timeline entries.")
    lines.append("")

    lines.append("## MITRE ATT&CK Techniques")
    techniques = incident.attack_techniques or []
    if techniques:
        for t in techniques:
            lines.append(f"- **{t.get('id')}** — {t.get('name')}")
    else:
        lines.append("None mapped.")
    lines.append("")

    actions = incident.recommended_actions or {}
    for section, label in (("immediate", "Immediate Containment"), ("investigation", "Investigation Steps"), ("recovery", "Recovery")):
        lines.append(f"## Recommended Response — {label}")
        items = actions.get(section, [])
        if items:
            lines.extend(f"- {a}" for a in items)
        else:
            lines.append("None.")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by GARUDA — Agentic AI Cybersecurity Assistant. Incident ID: {incident.incident_id}*")
    return "\n".join(lines)


def build_incident_report_pdf(incident: models.Incident) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    styles = getSampleStyleSheet()
    h1 = styles["Heading1"]
    h2 = styles["Heading2"]
    body = styles["BodyText"]
    small = ParagraphStyle("small", parent=body, fontSize=9, textColor=colors.grey)

    story = []
    story.append(Paragraph("GARUDA Incident Report", h1))
    story.append(Paragraph(
        f"Incident ID: {incident.incident_id} &nbsp;|&nbsp; Generated: {incident.updated_at}", small,
    ))
    story.append(Spacer(1, 0.2 * inch))

    meta = [
        ["Title", incident.title],
        ["Severity", incident.severity.upper()],
        ["Risk Score", f"{incident.risk_score}/100"],
        ["Status", incident.investigation_status],
        ["Source IP(s)", ", ".join((incident.entities or {}).get("source_ips", [])) or "-"],
        ["Destination IP(s)", ", ".join((incident.entities or {}).get("dest_ips", [])) or "-"],
        ["Affected Host(s)", ", ".join((incident.entities or {}).get("hosts", [])) or "-"],
        ["User(s)", ", ".join((incident.entities or {}).get("users", [])) or "-"],
    ]
    table = Table(meta, colWidths=[1.8 * inch, 4.5 * inch])
    table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#334155")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.25 * inch))

    story.append(Paragraph("Executive Summary", h2))
    story.append(Paragraph(incident.investigation_summary or "No investigation summary available.", body))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Attack Timeline", h2))
    for entry in incident.timeline or []:
        story.append(Paragraph(f"<b>{entry['timestamp']}</b> &mdash; {entry['description']}", body))
    if not incident.timeline:
        story.append(Paragraph("No timeline entries.", body))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Detected Threats &amp; Findings", h2))
    for f in incident.log_analysis_findings or []:
        tech = f.get("technique") or {}
        tech_str = f" [{tech.get('id')} {tech.get('name')}]" if tech.get("id") else ""
        story.append(Paragraph(
            f"<b>{f['finding']}</b>{tech_str} &mdash; confidence {round((f.get('confidence') or 0) * 100)}%, "
            f"severity {f.get('severity')}. Evidence: {f.get('evidence')}", body,
        ))
    if not incident.log_analysis_findings:
        story.append(Paragraph("No findings recorded.", body))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("MITRE ATT&amp;CK Techniques", h2))
    techniques = incident.attack_techniques or []
    if techniques:
        for t in techniques:
            story.append(Paragraph(f"&bull; {t.get('id')} — {t.get('name')}", body))
    else:
        story.append(Paragraph("None mapped.", body))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Risk Assessment", h2))
    rf = incident.risk_factors or {}
    rf_lines = [f"{k.replace('_', ' ').title()}: {v}" for k, v in rf.items()]
    story.extend(_bullet_list(rf_lines, body))
    story.append(Spacer(1, 0.2 * inch))

    actions = incident.recommended_actions or {}
    for section, label in (("immediate", "Immediate Containment"), ("investigation", "Investigation Steps"), ("recovery", "Recovery")):
        story.append(Paragraph(label, h2))
        story.extend(_bullet_list(actions.get(section, []), body))
        story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Final Conclusion", h2))
    story.append(Paragraph(
        f"This incident was classified as {incident.severity.upper()} with a risk score of "
        f"{incident.risk_score}/100. {incident.investigation_summary or ''}", body,
    ))

    doc.build(story)
    return buf.getvalue()
